version: '3.1'
services:
  busybox:
    container_name: busybox
    image: busybox:latest
    stdin_open: true
    tty: true
    restart: always
    working_dir: /home
    command: ash
    volumes:
      - .:/home